config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/about', 	to:'static_pages#about'
  get '/faq', 		to:'static_pages#faq'
  get '/contact', 	to:'static_pages#contact'
  get '/signup', 	to:'users#new'
  post '/signup', 	to:'users#create'
  get '/login',		to:'sessions#new'
  post '/login',	to:'sessions#create'
  delete '/logout', to:'sessions#delete'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:edit, :new, :create, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	attr_accessor :activation_token, :password_reset_token

	#Hooks
	before_save :downcase_email
	before_create :create_activation_digest

	#Validations
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: {case_sensitive: false}
    validates :password, presence: true, length: {  minimum: 6  }, allow_nil: true
    has_secure_password

    def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		                                              BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Returns true if the given token matches the digest.
	def authenticated?(attribute, token)
		digest = self.send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	# Activates an account.
	def activate
		update_attribute(:activated,    true)
		update_attribute(:activated_at, Time.zone.now)
	end

	# Sends activation email.
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	# Password Rest

	def create_reset_digest
		self.password_reset_token = User.new_token
		update_attribute(:reset_digest, User.digest(password_reset_token))
		update_attribute(:reset_sent_at, Time.zone.now)
	end

	def send_password_reset
		UserMailer.password_reset(self).deliver_now
	end

	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end

	private

		def downcase_email
			self.email.downcase!
		end

		def create_activation_digest
			self.activation_token = User.new_token
			self.activation_digest = User.digest(activation_token)
		end




end 

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      login user
      flash[:success] = "Account activated!"
      redirect_to user
    else
      flash[:danger] = "Invalid activation link"
      redirect_to login_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :validate_user, only: [:edit, :update]
  before_action :not_expired, only: [:edit, :update]

  def new
  end

  def edit
  end

  def update # This method is called by submit on password_reset/edit
    if(params[:user][:password].empty?)
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif (@user.update_attributes(user_params))
      login @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = 'Password reset successfully.'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create # This method is called by submit on password_reset/new
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if !@user.nil?
      #create token, store to user, send email
      @user.create_reset_digest
      @user.send_password_reset
      flash[:success] = "Check your email for a password reset email"
      redirect_to login_path
    else
      flash.now[:danger] = 'Email address not found'
      render 'new'
    end
  end

  private

    def get_user
      @user = User.find_by(email: params[:email].downcase)
    end

    def validate_user
      unless(@user && @user.activated && @user.authenticated?(:reset, params["id"]))
        redirect_to login_url
      end
    end

    def not_expired
      if @user.password_reset_expired?
        flash[:danger] = "Password reset link was expired."
        redirect_to new_password_reset_url
      end
    end

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
      if user.activated
        flash[:success] = "Successfully logged in"
        login user
        redirect_to user
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to login_url
      end
  	else
  		flash.now[:danger] = "Email/Password combination was incorrect"
  		render 'new'
  	end
  end

  def delete
    log_out if logged_in
    redirect_to login_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def home
  end

  def faq
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(param_user)
  	if @user.save
      @user.send_activation_email
  		flash[:info] = "Please check your email to activate your account."
  		redirect_to login_url
  	else
  		render 'new'
  	end
  end

  private

 	def param_user
 		params.require(:user).permit(:name, :email, :password, :password_confirmation)
 	end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title='')
		base_title = "Donate When Trump Tweets"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in
		!session[:user_id].nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil;
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, size: 80)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_error_explaination_flash.html.haml
.error-explanation
  - flash.each do |type,message|
    %div{class:"alert alert-#{type}"}
      = message

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    Donate When Trump Tweets
    by
    Joshua Philpott
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path

app/views/layouts/_nav.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
	.container
		= link_to "#Resist", root_path, id: "logo"
		%nav
			%ul.nav.navbar-nav.navbar-right
				%li= link_to "Home", root_path
				- if logged_in
					%li= link_to "Users", '#'
					%li.dropdown
						%a{href:"#", class:"dropdown-toggle", :'data-toggle'=>"dropdown"}
							Account
							%b.caret
						%ul.dropdown-menu
							%li= link_to "Profile", current_user
							%li= link_to "Settings", '#'
							%li.divider
							%li= link_to "Sign Out", logout_path, method: :delete
				- else
					%li= link_to "FAQ", faq_path
					%li= link_to "Log In", login_path

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.haml
/[if lt IE 9]
			%script{:type => "text/javascript",
				:src  => "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"}

app/views/layouts/application.html.haml
!!! HTML
%html
	%head
		%title= full_title yield :title
		= render 'layouts/rails_default'
		= render 'layouts/shim'
	%body
		= render 'layouts/nav'
		.container
			= yield
		= render 'layouts/footer'
		= debug(params) if Rails.env.development?

app/views/password_resets/edit.html.haml
=provide(:title, "Reset Password")
%h1 Reset Password
.row
  .col-md-6.col-md-offset-3
    = form_for(@user, url: password_reset_path(params[:id])) do |f|
      = render 'shared/error_messages'

      =hidden_field_tag :email, @user.email

      =f.label :password
      =f.password_field :password, class: 'form-control'

      =f.label :confirm
      =f.password_field :confirm, class: 'form-control'

      =f.submit "Submit", class: "btn btn-primary"

app/views/password_resets/new.html.haml
=provide(:title, "Forgot Password")
%h1 Reset Password
.row
  .col-md-6.col-md-offset-3
    = form_for(:password_reset, url: password_resets_path) do |f|
      = render 'layouts/error_explaination_flash'
      =f.label :email
      =f.email_field :email, class: 'form-control'

      =f.submit "Submit", class: "btn btn-primary"

app/views/shared/_error_messages.html.haml
-if @user.errors.any?
	.error_explanation
		.alert.alert-danger
			The form contains
			= pluralize(@user.errors.count, "error")
		%ul
			- @user.errors.full_messages.each do |msg|
				%li= msg

app/views/static_pages/about.html.haml
= provide(:title, 'About')
%h1 StaticPages#about
%p Find me in app/views/static_pages/about.html.haml

app/views/static_pages/contact.html.haml
= provide(:title, 'Contact')
%h1 Contact
%p 
	Contact Form? Probably not necessary.

app/views/static_pages/faq.html.haml
= provide(:title, 'FAQ')
%h1 FAQ
%p 
	This is the FAQ for DWTT
%h3 This is a question?
%p This is an answer.

app/views/static_pages/home.html.haml
.center.jumbotron
	%h1 Donate when Trump Tweets
	%h2
		Everytime @RealDonaldTrump sends a tweet, send a donation to your favorite charity.
	= link_to "Start Donating Now!", signup_path, class: "btn btn-lg btn-primary"
.row
	.col-md-12.text-center
		%h3 Thanks Donnie. Your tweets have sent $1,201,253.55 to our causes.
		<a class="twitter-timeline" href="https://twitter.com/RealDonaldTrump"></a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/users/new.html.haml
=provide(:title, "Sign Up")
%h1 Sign Up
.row
	.col-md-6.col-md-offset-3
		= form_for(@user, url: signup_path) do |f|
			=render 'shared/error_messages'
			=f.label :name 
			=f.text_field :name, class: 'form-control'

			=f.label :email
			=f.email_field :email, class: 'form-control'

			=f.label :password
			=f.password_field :password, class: 'form-control'

			=f.label :password_confirmation, "Confirmation"
			=f.password_field :password_confirmation , class: 'form-control'

			=f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.haml
- flash.each do |type, message|
	%div{class: "alert alert-#{type}"}
		= message
.row
	%aside.col-md-4
		%section.user_info
			%h1
				=gravatar_for @user
				=@user.name